### ISSUE TITLE
[NODE] SQL "Operation timed out"

### ISSUE THREAD

**Issue by yorickdowne** [smartcontractkit/chainlink#4282]
**Description**

I am seeing "Operation timed out" messages on the chainlink node, intermittently. I started troubleshooting PGSQL; I now think there is a chance this is on the CL node side, not the PGSQL side.

I have two test systems. One uses a fully HA PGSQL, sync mode. When the timeout occurred, I looked at the PGSQL logs: No long-running query reported, which suggest it may have been a networking issue.

The second test system is a dev box, with everything local: PGSQL and Chainlink node in docker containers. And I am seeing the messages there, if less frequently.

Since there is no way I have networking issues when staying on the same host, something else is going on. What that something else is, now that is a good question.

I'll run any debugs / tests you'd like me to, and I'd also love to hear whether you see this in your own dev environments.

Logs from dev box, to keep it simple:

```
yorick@ethlinux:~/link-docker$ docker-compose logs -f chainlink | grep "timed out"
chainlink_1     | 2021-04-21T13:57:38Z [WARN]  Operation timed out                                orm/orm.go:1193                  elapsed=1124.501693 rows=1 sql=INSERT INTO "heads" ("hash","number","parent_hash","timestamp","created_at") VALUES ('0x86a4cb6cfa71c6055680e484276d72c1aa764a9fa6c28afd72b8bd9296c06e59',24374470,'0xc82207218be7b84527652b2715817cd6f56a25399931f998feced0728ebde813','2021-04-21 13:57:36','2021-04-21 13:57:37.292') ON CONFLICT ("hash") DO NOTHING RETURNING "id"
chainlink_1     | 2021-04-23T07:47:17Z [WARN]  Operation timed out                                orm/orm.go:1193                  elapsed=1083.476179 rows=1 sql=INSERT INTO "heads" ("hash","number","parent_hash","timestamp","created_at") VALUES ('0x0f1ea7d020711d25d427b912f12972137bf151c73f65d0077fe20e650b73417e',24411582,'0x1581251d8119b63eee19df721c15ef162d28fcf363709603e214a3c151a18c2d','2021-04-23 07:47:16','2021-04-23 07:47:16.874') ON CONFLICT ("hash") DO NOTHING RETURNING "id"
chainlink_1     | 2021-04-26T07:31:05Z [WARN]  Operation timed out                                orm/orm.go:1193                  elapsed=1015.252224 rows=1 sql=INSERT INTO "heads" ("hash","number","parent_hash","timestamp","created_at") VALUES ('0x2209cb17d492f731ee37bb298717bd8ab28113790f6a30edbb4327ba7e5c0193',24474864,'0x7e73551ffd58413e1bbd234e8507a9b68533075b06d89c6e1229f84a027cab41','2021-04-26 07:31:04','2021-04-26 07:31:04.391') ON CONFLICT ("hash") DO NOTHING RETURNING "id"
```

**Basic Information**

- Network: Kovan
- Blockchain Client: OpenEthereum 3.2.4
- Operating System: Ubuntu 20.04
- Commit: Chainlink Node 0.10.4 at commit 1f76904abc1016d1d1c3946676a3fa125e33e550
- Startup Command: 
```
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - ETH_CHAIN_ID=${NETWORK_ID}
      - LINK_CONTRACT_ADDRESS=${LINK_CONTRACT_ADDRESS}
      - ETH_URL=ws://eth1-proxy:4000/
#      - ETH_SECONDARY_URLS=${ETH1_FAILOVER_NODE}
      - CHAINLINK_PORT=${CHAIN_PORT}
      - CHAINLINK_TLS_PORT=${CHAIN_TLS_PORT}
      - DATABASE_URL=${PGSQL_URL}
      - MINIMUM_CONTRACT_PAYMENT=${MIN_PAY}
      - OPERATOR_CONTRACT_ADDRESS=${OPERATOR_CONTRACT}
    ports:
      - ${CHAIN_PORT}:${CHAIN_PORT}/tcp
      - ${CHAIN_TLS_PORT}:${CHAIN_TLS_PORT}/tcp
    volumes:
      - chainlink-data:/var/lib/chainlink/
      - ./.secrets:/secrets
    entrypoint: wait-for-pgsql.sh ${PGSQL_URL} chainlink
    command: node start --password /secrets/wallet-password.txt --api /secrets/apicredentials.txt
```

**Environment Variables**

Content of `chainlink.env`:
```
ROOT=/var/lib/chainlink
MIN_OUTGOING_CONFIRMATIONS=2
TLS_CERT_PATH=/secrets/tls/server.crt
TLS_KEY_PATH=/secrets/tls/server.key
CHAINLINK_TLS_REDIRECT=true
GAS_UPDATER_ENABLED=true
FEATURE_FLUX_MONITOR=true
ALLOW_ORIGINS=*
DATABASE_TIMEOUT=0
```

Content of `.env`:

```
# Version of chainlink node to run
CHAIN_DOCKER_TAG=0.10.4
# Client choice: See README.md for available options
COMPOSE_FILE=chainlink.yml:pgsql.yml
# ETH1 endpoint / chain source. This default uses the eth1 node container
ETH1_NODE_1=wss://kovan.infura.io/ws/v3/{ID-REMOVED}
# Backup ETH1 sources via eth1 proxy, ws:// or wss://. This could be fiews, infura, alchemy, or an eth1 running on a different host
ETH1_NODE_2=
ETH1_NODE_3=
# Not in use currently: CL node built-in failover, https:// only. This proved to be too limited
# for production use.
#ETH1_FAILOVER_NODE=https://NETWORK.infura.io/v3/PROJECTID
#DB URL with TLS CA cert, make sure cert file is present and TLS enabled on PGSQL. This assumes DB name chainlink.
PGSQL_URL=postgresql://postgres:postgres@pg_chainlink:5432/chainlink?sslmode=disable
#Operator/Oracle Contract address, used to filter addresses node should listen to for runlogs. Can be left at default until contract has been deployed.
#Restart node after adjusting this value here
OPERATOR_CONTRACT=0x0000000000000000000000000000000000000000
# Network ID to use for Chainlink. 1 Mainnet, 42 Kovan, 4 Rinkeby, 3 Ropsten, 5 Goerli
# Rinkeby is only supported by Geth, Kovan only by OpenEthereum and Nethermind
NETWORK_ID=42
# Network to use for eth1. If using main net, set to mainnet.
ETH1_NETWORK=kovan
# Contract address for the LINK token, depends on the network
# Mainnet
#LINK_CONTRACT_ADDRESS=0x514910771af9ca656af840dff83e8264ecf986ca
# Kovan
LINK_CONTRACT_ADDRESS=0xa36085F69e2889c224210F603D836748e7dC0088
# Rinkeby
#LINK_CONTRACT_ADDRESS=0x01BE23585060835E02B77ef475b0Cc51aA1e0709
# Ropsten
#LINK_CONTRACT_ADDRESS=0x20fE562d797A42Dcb3399062AE9546cd06f63280
# Goerli
#LINK_CONTRACT_ADDRESS=0x326c977e6efc84e512bb9c30f76e30c160ed06fb
# Minimum contract payment - this is 1 LINK
MIN_PAY=100000000000000000

# Local Chainlink Web UI port. Do not expose to Internet, it is insecure http. TLS port can be exposed.
CHAIN_PORT=6688
CHAIN_TLS_PORT=8443
# P2P ports you will forward to your eth1 node. Adjust here if you are
# going to use something other than defaults.
ETH1_PORT=30303
# ETH1 WS port
ETH1_WS_PORT=8546

# Restart policy: Set to no if you do not want services to automatically restart
RESTART=unless-stopped
# If you want debug logs, set this to debug instead of info
LOG_LEVEL=info

# You can set specific version targets and choose
# binary or source builds below.

PG_DOCKER_TAG=13.1
```
