### ISSUE TITLE
Source "smartcontractkit/chainlink-brownie-contracts@1.1.1/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol" not found: File not found

### ISSUE THREAD

**Issue by mish1010** [smartcontractkit/chainlink#5505]
Hi @PatrickAlphaC , I am still having this issue on Lottery.sol. I had before but just followed along with tutorial. Since its about new lesson section I tried all solutions that found on the internet but did not work.

**Lottery.sol**
```
//SPDX-License-Identifier: MIT

pragma solidity ^0.6.6;

import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";

contract Lottery {
    address payable[] public players;
    uint256 public usdEntryFree;
    AggregatorV3Interface internal ethUsdPriceFeed;

    constructor(_priceFeedAddress) public {
        usdEntryFree = 50 * (10**18);
        ethUsdPriceFeed = AggregatorV3Interface(_priceFeedAddress);
    }

    function enter() public payable {
        //50USD min
        players.push(msg.sender);
    }

    function getEntranceFee() public view returns (uint256) {}

    function startLottery() public {}

    function endLottery() public {}
}

```

**brownie-config.yaml**

```
dependecies:
 - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
   remappings:
     - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
     
     
     
```

I have tried to remove "-" on remappings.

I have tried to separate on AggregatorV3Interface on Lottery.sol

I imported AggregatorV3.sol as a file to contracts

I tried to change versions
 
but still no luck. I am using Mac M1 - can it be the reason due to chip?
