### ISSUE TITLE
[NODE] How to specify API credentials while running chainlink node image smartcontract/chainlink:2.0.0 or above in configurations

### ISSUE THREAD

**Issue by kashif-ghafoor** [smartcontractkit/chainlink#9729]
**Description**
There is no way to specify api email and password in some configuration file if I want to run chainlink node in detached docker mode or run it using docker compose.I don't want to enter api email and password in terminal while setting up node for first time. I need a way to specify api email and password in configurations. 

I tried to specify it in .api file and then used -a flag to point to this file. but got error that -a flag is not defined. It is not specified anywhere in the [documentation](https://docs.chain.link/chainlink-nodes/v1/running-a-chainlink-node)

**Basic Information**
following is content of docker-compose.yml that I am using for further context

```yaml
version: "3"
services:
  cl-postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: kashifPostgresPassword
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  chainlink:
    image: smartcontract/chainlink:2.0.0
    platform: linux/x86_64/v8
    command: node -config /chainlink/config.toml -secrets /chainlink/secrets.toml start
    volumes:
      - ~/.chainlink-sepolia:/chainlink
    ports:
      - 6688:6688
    depends_on:
      - cl-postgres

volumes:
  db_data:
```
logs
```
Attaching to chainlink-chainlink-1, chainlink-cl-postgres-1
chainlink-cl-postgres-1  | 
chainlink-cl-postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
chainlink-cl-postgres-1  | 
chainlink-cl-postgres-1  | 2023-06-30 22:51:13.666 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
chainlink-cl-postgres-1  | 2023-06-30 22:51:13.667 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
chainlink-cl-postgres-1  | 2023-06-30 22:51:13.667 UTC [1] LOG:  listening on IPv6 address "::", port 5432
chainlink-cl-postgres-1  | 2023-06-30 22:51:13.684 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
chainlink-cl-postgres-1  | 2023-06-30 22:51:13.700 UTC [27] LOG:  database system was shut down at 2023-06-30 22:51:09 UTC
chainlink-cl-postgres-1  | 2023-06-30 22:51:13.723 UTC [1] LOG:  database system is ready to accept connections
chainlink-cl-postgres-1  | 2023-06-30 22:51:14.656 UTC [32] ERROR:  relation "migrations" does not exist at character 16
chainlink-cl-postgres-1  | 2023-06-30 22:51:14.656 UTC [32] STATEMENT:  SELECT id FROM migrations
chainlink-chainlink-1    | 2023/06/30 22:51:14 goose: no migrations to run. current version: 167
chainlink-chainlink-1    | 2023-06-30T22:51:14.685Z [WARN]  P2PListenPort was not set, listening on random port 33037. A new random port will be generated on every boot, for stability it is recommended to set P2PListenPort to a fixed value in your environment chainlink/config_general.go:828  p2pPort=33037 
chainlink-chainlink-1    | API credentials must be supplied
chainlink-chainlink-1 exited with code 1
chainlink-cl-postgres-1  | 2023-06-30 22:56:13.821 UTC [25] LOG:  checkpoint starting: time
chainlink-cl-postgres-1  | 2023-06-30 22:56:14.502 UTC [25] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.632 s, sync=0.019 s, total=0.681 s; sync files=8, longest=0.016 s, average=0.003 s; distance=6 kB, estimate=6 kB
```
